[project]
name = "core"
version = "0.1.0"
description = "Shared Python code for ReelsappAI"
authors = [
    { name = "Gemini", email = "gemini@google.com" },
]
dependencies = []
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
